// @vitest-environment jsdom
import { beforeEach, describe, expect, it, vi } from "vitest";

const invokeState = vi.hoisted(() => ({
  calls: [] as Array<{ command: string; args: unknown; options?: unknown }>,
  handler: undefined as
    | ((command: string, args?: unknown, options?: unknown) => unknown)
    | undefined,
}));

vi.mock("@tauri-apps/api/core", () => ({
  invoke: async (command: string, args?: unknown, options?: unknown) => {
    const call: { command: string; args: unknown; options?: unknown } = { command, args };

    if (options !== undefined) {
      call.options = options;
    }

    invokeState.calls.push(call);

    if (!invokeState.handler) {
      throw new Error(`Unexpected invoke: ${command}`);
    }

    return invokeState.handler(command, args, options);
  },
}));

beforeEach(() => {
  vi.resetModules();
  invokeState.calls.length = 0;
  Object.defineProperty(window, "__TAURI_INTERNALS__", {
    value: {},
    configurable: true,
  });
  invokeState.handler = (command) => {
    if (command === "save_pdf_dialog") {
      return { fileGrant: "caption-grant", name: "caption.pdf" };
    }

    throw new Error(`Unexpected invoke: ${command}`);
  };
});

describe("saveCaptionPdf", () => {
  it("renders in-process and writes the generated bytes through save_pdf_dialog", async () => {
    const { saveCaptionPdf } = await import("./captionActions");
    const saved = await saveCaptionPdf({
      styleId: "minimal",
      caption: {
        courtName: "Circuit Court",
        parties: [{ role: "Plaintiff", names: ["Jane Smith"] }],
        documentTitle: "Notice of Filing",
      },
    }, "caption.pdf");

    expect(saved).toEqual({ name: "caption.pdf", path: "caption-grant" });
    expect(invokeState.calls).toHaveLength(1);
    expect(invokeState.calls[0]!.command).toBe("save_pdf_dialog");
    expect(invokeState.calls[0]!.args).toBeInstanceOf(Uint8Array);
    expect(invokeState.calls[0]!.options).toEqual({
      headers: {
        "x-raio-suggested-name": "caption.pdf",
      },
    });
  });
});
