// @vitest-environment jsdom
import { beforeEach, describe, expect, it, vi } from "vitest";

const invokeState = vi.hoisted(() => ({
  calls: [] as Array<{ command: string; args: unknown; options?: unknown }>,
  handler: undefined as
    | ((command: string, args?: unknown, options?: unknown) => unknown)
    | undefined,
}));

vi.mock("@tauri-apps/api/core", () => ({
  invoke: async (command: string, args?: unknown, options?: unknown) => {
    const call: { command: string; args: unknown; options?: unknown } = { command, args };

    if (options !== undefined) {
      call.options = options;
    }

    invokeState.calls.push(call);

    if (!invokeState.handler) {
      throw new Error(`Unexpected invoke: ${command}`);
    }

    return invokeState.handler(command, args, options);
  },
}));

beforeEach(() => {
  vi.resetModules();
  invokeState.calls.length = 0;
  Object.defineProperty(window, "__TAURI_INTERNALS__", {
    value: {},
    configurable: true,
  });
  invokeState.handler = (command) => {
    if (command === "save_pdf_dialog") {
      return { fileGrant: "toa-grant", name: "toa.pdf" };
    }

    throw new Error(`Unexpected invoke: ${command}`);
  };
});

describe("Table of Authorities actions", () => {
  it("builds engine options from reviewed rows", async () => {
    const { buildTableOfAuthoritiesOptions } = await import("./toaActions");

    expect(buildTableOfAuthoritiesOptions([
      {
        kind: "case",
        citation: " 123 So. 3d 456 ",
        pageIndexes: [2, 0, 2],
      },
      {
        kind: "statute",
        citation: "Fla. Stat. § 95.11",
        pageIndexes: [1],
        excluded: true,
      },
    ], 5)).toEqual({
      entries: [
        { kind: "case", citation: "123 So. 3d 456", pages: [1, 3] },
      ],
      passimThreshold: 5,
    });
  });

  it("renders in-process and writes generated bytes through save_pdf_dialog", async () => {
    const { saveToaPdf } = await import("./toaActions");
    const saved = await saveToaPdf([
      { kind: "case", citation: "123 So. 3d 456", pageIndexes: [0, 2] },
    ], 5, "toa.pdf");

    expect(saved).toEqual({ name: "toa.pdf", path: "toa-grant" });
    expect(invokeState.calls).toHaveLength(1);
    expect(invokeState.calls[0]!.command).toBe("save_pdf_dialog");
    expect(invokeState.calls[0]!.args).toBeInstanceOf(Uint8Array);
    expect(invokeState.calls[0]!.options).toEqual({
      headers: {
        "x-raio-suggested-name": "toa.pdf",
      },
    });
  });
});
